name: Pull request workflow

on:
  pull_request:
    branches:
      - developer/v1.0
  workflow_dispatch:

jobs:
  PR-job:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      

      # Order Service
      - name: Build order service
        uses: docker/build-push-action@v6
        with:
          context: ./src/order-service
          load: true
          tags: order-service:${{ github.event.pull_request.head.sha }}

      - name: Scan order service
        run: |
         trivy image \
          --format sarif \
          --output trivy-order-service.sarif \
          order-service:${{ github.event.pull_request.head.sha }}

      # Product Service
      - name: Build product service
        uses: docker/build-push-action@v6
        with:
          context: ./src/product-service
          load: true
          tags: product-service:${{ github.event.pull_request.head.sha }}

      - name: Scan product service
        run: |
         trivy image \
          --format sarif \
          --output trivy-product-service.sarif \
          product-service:${{ github.event.pull_request.head.sha }}

      # Store Front
      - name: Build store front
        uses: docker/build-push-action@v6
        with:
          context: ./src/store-front
          load: true
          tags: store-front:${{ github.event.pull_request.head.sha }}

      - name: Scan store front
        run: |
         trivy image \
          --format sarif \
          --output trivy-store-front.sarif \
          store-front:${{ github.event.pull_request.head.sha }}

      # Makeline
      - name: Build makeline service
        uses: docker/build-push-action@v6
        with:
          context: ./src/makeline-service
          load: true
          tags: makeline-service:${{ github.event.pull_request.head.sha }}

      - name: Scan makeline service
        run: |
         trivy image \
          --format sarif \
          --output trivy-makeline-service.sarif \
          makeline-service:${{ github.event.pull_request.head.sha }}

      # Store Admin
      - name: Build store admin
        uses: docker/build-push-action@v6
        with:
          context: ./src/store-admin
          load: true
          tags: store-admin:${{ github.event.pull_request.head.sha }}

      - name: Scan store admin
        run: |
         trivy image \
          --format sarif \
          --output trivy-store-admin.sarif \
          store-admin:${{ github.event.pull_request.head.sha }}

      # Virtual Customer
      - name: Build virtual customer
        uses: docker/build-push-action@v6
        with:
          context: ./src/virtual-customer
          load: true
          tags: virtual-customer:${{ github.event.pull_request.head.sha }}

      - name: Scan virtual customer
        run: |
         trivy image \
          --format sarif \
          --output trivy-virtual-customer.sarif \
          virtual-customer:${{ github.event.pull_request.head.sha }}

      # Virtual Worker
      - name: Build virtual worker
        uses: docker/build-push-action@v6
        with:
          context: ./src/virtual-worker
          load: true
          tags: virtual-worker:${{ github.event.pull_request.head.sha }}

      - name: Scan virtual worker
        run: |
         trivy image \
          --format sarif \
          --output trivy-virtual-worker.sarif \
          virtual-worker:${{ github.event.pull_request.head.sha }}
